#
# Makefile for the fpga framework and fpga manager drivers.
#

# Vicharak FPGA
obj-$(CONFIG_VICHARAK_FPGA)		+= vicharak/

# Core FPGA Manager Framework
obj-$(CONFIG_FPGA)			+= fpga-mgr.o

# FPGA Manager Drivers
obj-$(CONFIG_FPGA_MGR_SOCFPGA)		+= socfpga.o
obj-$(CONFIG_FPGA_MGR_ZYNQ_FPGA)	+= zynq-fpga.o
